# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "test"
  lane :release do
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
      submit_for_review: false,
      automatic_release: false,
      precheck_include_in_app_purchases: false,
      languages: ['en-US'],
      submission_information: { add_id_info_uses_idfa: false },
      release_notes: {
        'default' => "- a",
        'en-US' => "- a",
      },
      itc_provider: 'Y6F6QCVDBY')
  end

end