# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flutter-actions-android:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      
    - name: Setup java environment
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set Multi-line Variable
  run: |
    cat <<EOF >> $GITHUB_ENV
    TEST_JSON={
      "type": "service_account",
      "universe_domain": "googleapis.com",
      "key": "a\nb\nc\n"
    }
  EOF

    - name: Test get data
      run: |
        echo "$TEST_JSON"

        
