name: Android Deploy All Brand App

on:
  workflow_dispatch:

jobs:
  setup-brand-app-deployment-workflows:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Find Android GA workflows and set matrix
        id: set-matrix
        run: |
          echo "Searching for workflows matching *_android_ga.yml..."
          WORKFLOWS=$(find .github/workflows -name '*_android_ga.yml' | sed 's#.github/workflows/##')

          echo "Building matrix..."
          MATRIX="["

          for FILE in $WORKFLOWS; do
            PREFIX=$(echo "$FILE" | sed 's/_android_ga\.yml//')
            BRANCH="feature/master_$PREFIX"
            MATRIX="$MATRIX{\"workflow\":\"$FILE\",\"ref\":\"$BRANCH\"},"
          done

          MATRIX="${MATRIX%,}]"
          FINAL_MATRIX="{\"include\":$MATRIX}"
          echo "Generated matrix: $FINAL_MATRIX"

          echo "matrix=$FINAL_MATRIX" >> $GITHUB_OUTPUT

  dispatch-workflows:
    needs: find-workflows
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.find-workflows.outputs.matrix) }}
    steps:
      - name: Dispatch workflow ${{ matrix.workflow }} on ${{ matrix.ref }}
        uses: actions/github-script@v7
        with:
          script: |
            const workflow = "${{ matrix.workflow }}";
            const ref = "${{ matrix.ref }}";

            console.log(`Dispatching ${workflow} on ${ref}`);

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow,
              ref: ref
            });