# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flutter-actions-android:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    
    - name: Load secret
      uses: 1password/load-secrets-action@v2
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: 'ops_eyJzaWduSW5BZGRyZXNzIjoibXkuMXBhc3N3b3JkLmNvbSIsInVzZXJBdXRoIjp7Im1ldGhvZCI6IlNSUGctNDA5NiIsImFsZyI6IlBCRVMyZy1IUzI1NiIsIml0ZXJhdGlvbnMiOjY1MDAwMCwic2FsdCI6IkhUS0hUWmNneU13T0lRT1BKSk1yaXcifSwiZW1haWwiOiJqZ3M3NHV4bWZibmthQDFwYXNzd29yZHNlcnZpY2VhY2NvdW50cy5jb20iLCJzcnBYIjoiNzc2ZjkwOWEwOTkyNGNiODUzNWFiOTVjNTQ4OTU3NmQwODY1NTI3ZTA1MDgxMmM0ZjUxNzY3ZGMzODY3YTQ3MyIsIm11ayI6eyJhbGciOiJBMjU2R0NNIiwiZXh0Ijp0cnVlLCJrIjoicVZydEdlWHNib1VrRTRqUWFVZGRPem4zSTF3NEFkdXZyLXozdWJIN1YwMCIsImtleV9vcHMiOlsiZW5jcnlwdCIsImRlY3J5cHQiXSwia3R5Ijoib2N0Iiwia2lkIjoibXAifSwic2VjcmV0S2V5IjoiQTMtTDRDRTJNLVQ5MlRDQS01R0ZDWi00RllYUC0yTjc2Qy1SUkVIRiIsInRocm90dGxlU2VjcmV0Ijp7InNlZWQiOiI3YzgxZmZkOTYwNDM5MjhhY2E5ZWY5YTQxMjY2YjYwOTBkOWZlYjA4NTc2YTEzZDNlNGNlOTQ3OWYwMTZjYWY3IiwidXVpZCI6IkpRSlo3SFQ2M1pEVFpMSVhETFo1UlY1RE1RIn0sImRldmljZVV1aWQiOiJ3ZTJoYWtpajI3d3ZvNHZ2bXhoNGdjb2FyaSJ9'
        SECRET_STRING: op://Unimportant Test Vault/sample
    
    - name: Write secret string to file
      run: |
        echo "$SECRET_STRING" > secret_debug_output.txt

    - name: Upload secret file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: secret-debug-output
        path: secret_debug_output.txt
        retention-days: 1
        overwrite: true
    

    


        
